name: aronets_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  appmetrica_plugin: ^1.0.1
  cloud_firestore: ^3.4.5
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  firebase_database: ^9.1.2
  firebase_messaging: ^12.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^1.0.0
  flutter_native_splash: ^2.2.8
  intl: ^0.17.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#e1f5fe"
  color_dark: "#042a49"
  web_image_mode: center
  web: true
  image: assets/images/flutter_splash.png
  image_dark: assets/images/flutter_splash.png
