// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjjecyLji25--bSAFVkWeiCq02oWsVPQM',
    appId: '1:126188264955:web:e54088828e34fd91613f5e',
    messagingSenderId: '126188264955',
    projectId: 'aronets-web',
    authDomain: 'aronets-web.firebaseapp.com',
    databaseURL: 'https://aronets-web-default-rtdb.firebaseio.com',
    storageBucket: 'aronets-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9VUpHB2uklusjW4ouZfc4d6wsio0-Dbc',
    appId: '1:126188264955:android:cfa6400037b9f83c613f5e',
    messagingSenderId: '126188264955',
    projectId: 'aronets-web',
    databaseURL: 'https://aronets-web-default-rtdb.firebaseio.com',
    storageBucket: 'aronets-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMpLdsDnMAMHufEIxEKN2a_zbh3UJ94Yw',
    appId: '1:126188264955:ios:22573c2202b99329613f5e',
    messagingSenderId: '126188264955',
    projectId: 'aronets-web',
    databaseURL: 'https://aronets-web-default-rtdb.firebaseio.com',
    storageBucket: 'aronets-web.appspot.com',
    iosClientId: '126188264955-n9qjp903il7gt6eiudb8h2ee8f95v6kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.aronetsPortfolio',
  );
}
